language: cpp
compiler:
  - clang
  - gcc
os:
  - osx
  - linux
env:
  - CONFIG=Release
  - CONFIG=Debug
matrix:
  exclude:
  - os: osx
    compiler: gcc
before_install:
  - if [ $CC = gcc ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ $TRAVIS_OS_NAME = 'linux' -a $CC = 'clang' ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - $CC -v
  - ./devtools/travis-preinstall.sh
install:
  - ./devtools/travis-install.sh
script:
  - git submodule update --init --recursive;
  - mkdir build;
  - cd build;
  - if [ $TRAVIS_OS_NAME = 'osx' ]; then cmake .. -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_OSX_ARCHITECTURES=x86_64; fi
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then cmake .. -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_PREFIX_PATH=$INSTPRF; fi
  - make all -j2
# TODO need to sort out false-failures due to container/platform issues.
#  - "ctest -V"
sudo: false
addons:
  apt:
    sources:
    - boost-latest
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - libusb-1.0-0-dev
    - libboost-thread1.55-dev
    - libboost-system1.55-dev
    - libboost-date-time1.55-dev
    - libboost-chrono1.55-dev
    - libboost-program-options1.55-dev
    - libboost-filesystem1.55-dev
    - cmake-data
    - cmake
    - gcc-5
    - g++-5
    - clang-3.7
    - build-essential
    - git
    - libgtk2.0-dev
    - pkg-config
    - python-dev
    - python-numpy
    - libdc1394-22
    - libdc1394-22-dev
    - libjpeg-dev
    - libpng12-dev
    - libtiff4-dev
    - libjasper-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libxine-dev
    - libgstreamer0.10-dev
    - libgstreamer-plugins-base0.10-dev
    - libv4l-dev
    - libtbb-dev
    - libqt4-dev
    - libfaac-dev
    - libmp3lame-dev
    - libopencore-amrnb-dev
    - libopencore-amrwb-dev
    - libtheora-dev
    - libvorbis-dev
    - libxvidcore-dev
    - x264
    - v4l-utils
    - unzip
